<?php

/**
* @file
* This file demonstrates how to use hook functions.
*/


/**
* Implements hook_cron(). 
*/
function ycpcustom_cron() {
  \Drupal::messenger()->addMessage(t('Hello from YCP Custom cron hook!'));  
}


/**
* Implements hook_form_alter(). Renamed below. 
* NOTE: &$form is passed by reference, so we can change this.. 
* NOTE: Inspect the form, find the id, id="node-article-edit-form", need to replace - with _ as below.
* or use method \Drupal::messenger()->addMessage(t("form_id of this form is @id: ", ['@id' => $form_id]));
* This is called when a status message appears.
*/
/** THIS SHOWS UP WITH ANY STATUS MESSAGE WHEN YOU EDIT AN ARTICLE.
*function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
*  \Drupal::messenger()->addMessage(t("form_id of this form is @id: ", ['@id' => $form_id]));
*  if ($form_id == 'node_article_edit_form') {
*    $form['actions']['submit']['#value'] = t('Save this article now!');
*  }
*}
*/